-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- DROP TABLES IF THEY EXIST TO AVOID CONFLICTS
DROP TABLE IF EXISTS AI_REPORT CASCADE;
DROP TABLE IF EXISTS DETAILED CASCADE;
DROP TABLE IF EXISTS CATEGORY_BUDGET CASCADE;
DROP TABLE IF EXISTS USER_BUDGET CASCADE;
DROP TABLE IF EXISTS ACCOUNT_BUDGET CASCADE;
DROP TABLE IF EXISTS BUDGET CASCADE;
DROP TABLE IF EXISTS RECEIPT CASCADE;
DROP TABLE IF EXISTS EXPENSE_ITEMS CASCADE;
DROP TABLE IF EXISTS EXPENSES CASCADE;
DROP TABLE IF EXISTS EXPENSE_CATEGORY CASCADE;
DROP TABLE IF EXISTS INCOME CASCADE;
DROP TABLE IF EXISTS TRANSFER CASCADE;
DROP TABLE IF EXISTS TRANSACTION CASCADE;
DROP TABLE IF EXISTS ACCOUNTS CASCADE;
DROP TABLE IF EXISTS BIOMETRICS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;


---
-- 1. USER AUTHENTICATION & BIOMETRIC SECURITY MODULE
---

CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USERNAME TEXT UNIQUE NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER TEXT,
    EMAIL TEXT UNIQUE NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    VERIFIED_AT TIMESTAMPTZ,
    TIMEZONE TEXT DEFAULT '+08:00',
    THEME_PREF TEXT DEFAULT 'system',
    CURRENCY_PREF TEXT DEFAULT 'MYR',
    -- Constraint
    CONSTRAINT users_date_of_birth_current CHECK (DATE_OF_BIRTH <= CURRENT_DATE OR DATE_OF_BIRTH IS NULL),
    CONSTRAINT users_gender_options CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER') OR GENDER IS NULL),
    CONSTRAINT users_email_format CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT users_timezone_format CHECK (TIMEZONE ~ '^[+-](0[0-9]|1[0-4]):([0-5][0-9])$'),
    CONSTRAINT users_theme_pref_options CHECK (THEME_PREF IN ('light', 'dark', 'system') OR THEME_PREF IS NULL),
    CONSTRAINT users_currency_pref_format CHECK (CURRENCY_PREF ~* '^[A-Z]{3}$' OR CURRENCY_PREF IS NULL)
);

CREATE TABLE BIOMETRICS (
    BIOMETRIC_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEMPLATE_DATA TEXT NOT NULL,
    ALGO_VERSION TEXT NOT NULL,
    DEVICE_ID TEXT,
    DEVICE_NAME TEXT,
    TYPE TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_USED_AT TIMESTAMPTZ,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT biometrics_type_options CHECK (TYPE IN ('fingerprint', 'face') OR TYPE IS NULL)
);

---
-- 2. INCOME & EXPENSES MANAGEMENT MODULE
---

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    INITIAL_BALANCE NUMERIC(15, 2) DEFAULT 0,
    CURRENT_BALANCE NUMERIC(15, 2) DEFAULT 0,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT accounts_type_options CHECK (TYPE IN ('CASH', 'BANK', 'E-WALLET', 'CREDIT CARD', 'INVESTMENT', 'LOAN', 'OTHER'))
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME TEXT NOT NULL,
    TYPE CHAR(1) NOT NULL, 
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    CURRENCY TEXT,
    ACCOUNT_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT transaction_type_options CHECK (TYPE IN ('T', 'I', 'E')) -- T: Transfer, I: Income, E: Expense
);

CREATE TABLE TRANSFER (
    TRANSACTION_ID UUID PRIMARY KEY REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE,
    AMOUNT NUMERIC(15, 2) NOT NULL,
    FROM_ACCOUNT_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID) NOT NULL,
    TO_ACCOUNT_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID) NOT NULL,
    -- Constraint
    CONSTRAINT transfer_amount_positive CHECK (AMOUNT > 0),
    CONSTRAINT transfer_accounts_different CHECK (FROM_ACCOUNT_ID <> TO_ACCOUNT_ID)
);

CREATE TABLE INCOME (
    TRANSACTION_ID UUID PRIMARY KEY REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE,
    AMOUNT NUMERIC(15, 2) NOT NULL,
    CATEGORY TEXT,
    IS_RECURRENT BOOLEAN DEFAULT FALSE,
    -- Constraint
    CONSTRAINT income_amount_positive CHECK (AMOUNT > 0),
    CONSTRAINT income_category_options CHECK (CATEGORY IN ('SALARY', 'BUSINESS', 'GIFT', 'INVESTMENT', 'OTHER') OR CATEGORY IS NULL)
);

---
-- 4. EXPENSE ENTRY & OCR MODULE
---

CREATE TABLE EXPENSE_CATEGORY (
    EXPENSE_CAT_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    -- Constraint
    CONSTRAINT expense_category_name_options CHECK (NAME IN
    ('FOOD', 'TRANSPORT', 'ENTERTAINMENT', 'UTILITIES', 'HEALTHCARE',
    'SHOPPING', 'TRAVEL', 'EDUCATION', 'RENT', 'OTHER')
    OR NAME IS NULL)
);

CREATE TABLE EXPENSES (
    TRANSACTION_ID UUID PRIMARY KEY REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE,
    AMOUNT NUMERIC(15, 2) NOT NULL,
    EXPENSE_CAT_ID UUID REFERENCES EXPENSE_CATEGORY(EXPENSE_CAT_ID),
    -- Constraint
    CONSTRAINT expenses_amount_positive CHECK (AMOUNT > 0)
);

CREATE TABLE EXPENSE_ITEMS (
    TRANSACTION_ID UUID REFERENCES EXPENSES(TRANSACTION_ID) ON DELETE CASCADE,
    ITEM_ID INTEGER,
    ITEM_NAME TEXT,
    QTY INTEGER DEFAULT 1,
    UNIT_PRICE NUMERIC(15, 2) DEFAULT 0,
    PRICE NUMERIC(15, 2) DEFAULT 0,
    -- Primary Key
    PRIMARY KEY (TRANSACTION_ID, ITEM_ID),
    -- Constraint
    CONSTRAINT expense_items_qty_positive CHECK (QTY > 0),
    CONSTRAINT expense_items_unit_price_nonnegative CHECK (UNIT_PRICE >= 0),
    CONSTRAINT expense_items_price_nonnegative CHECK (PRICE >= 0),
    CONSTRAINT expense_items_price_consistency CHECK (PRICE = QTY * UNIT_PRICE)
);

CREATE TABLE RECEIPT (
    RECEIPT_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    PATH TEXT NOT NULL,
    MERCHANT_NAME TEXT,
    CONFIDENCE_SCORE NUMERIC(5, 2),
    OCR_RAW_TEXT TEXT,
    SCANNED_AT TIMESTAMPTZ DEFAULT NOW(),
    TRANSACTION_ID UUID REFERENCES TRANSACTION(TRANSACTION_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT receipt_confidence_score_range CHECK (CONFIDENCE_SCORE >= 0 AND CONFIDENCE_SCORE <= 100)
);

---
-- 3. BUDGET & THRESHOLD MODULE
---

CREATE TABLE BUDGET (
    BUDGET_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TYPE CHAR(1) NOT NULL, 
    DATE_FROM DATE NOT NULL,
    DATE_TO DATE NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT budget_dates_consistency CHECK (DATE_TO >= DATE_FROM),
    CONSTRAINT budget_type_options CHECK (TYPE IN ('A', 'U', 'C')) -- A: Account, U: User, C: Category
);

CREATE TABLE USER_BUDGET (
    BUDGET_ID UUID PRIMARY KEY REFERENCES BUDGET(BUDGET_ID) ON DELETE CASCADE,
    THRESHOLD NUMERIC(15, 2) NOT NULL,
    -- Constraint
    CONSTRAINT user_budget_threshold_positive CHECK (THRESHOLD > 0)
);

CREATE TABLE ACCOUNT_BUDGET (
    BUDGET_ID UUID PRIMARY KEY REFERENCES BUDGET(BUDGET_ID) ON DELETE CASCADE,
    THRESHOLD NUMERIC(15, 2) NOT NULL,
    ACCOUNT_ID UUID REFERENCES ACCOUNTS(ACCOUNT_ID),
    -- Constraint
    CONSTRAINT account_budget_threshold_positive CHECK (THRESHOLD > 0)
);

CREATE TABLE CATEGORY_BUDGET (
    BUDGET_ID UUID PRIMARY KEY REFERENCES BUDGET(BUDGET_ID) ON DELETE CASCADE,
    THRESHOLD NUMERIC(15, 2) NOT NULL,
    EXPENSE_CAT_ID UUID REFERENCES EXPENSE_CATEGORY(EXPENSE_CAT_ID),
    -- Constraint
    CONSTRAINT category_budget_threshold_positive CHECK (THRESHOLD > 0)
);


---
-- 5. AI FINANCIAL HEALTH SCORE & INSIGHTS MODULE
---

CREATE TABLE DETAILED (
    DETAILED_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    EDU_LVL TEXT,
    EMPLOYMENT_STAT BOOLEAN DEFAULT FALSE,
    MARITAL_STAT BOOLEAN DEFAULT FALSE,
    DEPENDENT_NUM INTEGER DEFAULT 0,
    ESTIMATED_LOAN NUMERIC(15, 2) DEFAULT 0,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT detailed_edu_lvl_options CHECK (EDU_LVL IN ('NONE', 'HIGH SCHOOL', 'ASSOCIATE', 'DIPLOMA', 'BACHELORS', 'MASTERS', 'PHD', 'OTHER') OR EDU_LVL IS NULL),
    CONSTRAINT detailed_dependent_num_nonnegative CHECK (DEPENDENT_NUM >= 0),
    CONSTRAINT detailed_estimated_loan_nonnegative CHECK (ESTIMATED_LOAN >= 0)
);

CREATE TABLE AI_REPORT (
    REPORT_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TITLE TEXT,
    DESCRIPTION TEXT,
    BODY TEXT,
    MONTH TEXT,
    HEALTH_SCORE INTEGER,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    -- Constraint
    CONSTRAINT month_format CHECK (MONTH ~ '^(0[1-9]|1[0-2])-(\d{4})$' OR MONTH IS NULL),
    CONSTRAINT check_health_score_range CHECK (HEALTH_SCORE >= 0 AND HEALTH_SCORE <= 100)
);