class ProfileConstants {
  static const List<String> timezones = [
    "(UTC-12:00) International Date Line West",
    "(UTC-11:00) Midway Island, Samoa",
    "(UTC-10:00) Hawaii",
    "(UTC-09:00) Alaska",
    "(UTC-08:00) Pacific Time (US & Canada)",
    "(UTC-07:00) Mountain Time (US & Canada)",
    "(UTC-06:00) Central Time (US & Canada)",
    "(UTC-05:00) Eastern Time (US & Canada)",
    "(UTC-04:30) Caracas",
    "(UTC-04:00) Atlantic Time (Canada), La Paz",
    "(UTC-03:30) Newfoundland",
    "(UTC-03:00) Brasilia, Buenos Aires, Georgetown",
    "(UTC-02:00) Mid-Atlantic",
    "(UTC-01:00) Azores, Cape Verde Is.",
    "(UTC+00:00) London, Dublin, Edinburgh, Lisbon, Monrovia",
    "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "(UTC+02:00) Cairo, Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    "(UTC+03:00) Baghdad, Kuwait, Riyadh, Moscow, St. Petersburg",
    "(UTC+03:30) Tehran",
    "(UTC+04:00) Abu Dhabi, Muscat, Baku, Tbilisi, Yerevan",
    "(UTC+04:30) Kabul",
    "(UTC+05:00) Islamabad, Karachi, Tashkent",
    "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    "(UTC+05:45) Kathmandu",
    "(UTC+06:00) Almaty, Dhaka, Astana",
    "(UTC+06:30) Yangon (Rangoon)",
    "(UTC+07:00) Bangkok, Hanoi, Jakarta",
    "(UTC+08:00) Kuala Lumpur, Singapore, Beijing, Perth",
    "(UTC+09:00) Osaka, Sapporo, Tokyo, Seoul",
    "(UTC+09:30) Adelaide, Darwin",
    "(UTC+10:00) Canberra, Melbourne, Sydney, Guam",
    "(UTC+11:00) Magadan, Solomon Is., New Caledonia",
    "(UTC+12:00) Auckland, Wellington, Fiji, Kamchatka",
    "(UTC+13:00) Nuku'alofa",
  ];

  static const List<String> currencies = [
    "USD - United States Dollar",
    "EUR - Euro",
    "GBP - British Pound",
    "JPY - Japanese Yen",
    "CNY - Chinese Yuan",
    "MYR - Malaysian Ringgit",
    "SGD - Singapore Dollar",
    "INR - Indian Rupee",
    "AUD - Australian Dollar",
    "CAD - Canadian Dollar",
    "HKD - Hong Kong Dollar",
    "KRW - South Korean Won",
    "IDR - Indonesian Rupiah",
    "PHP - Philippine Peso",
    "THB - Thai Baht",
    "VND - Vietnamese Dong",
    "BRL - Brazilian Real",
    "RUB - Russian Ruble",
    "NZD - New Zealand Dollar",
    "MXN - Mexican Peso",
    "SAR - Saudi Riyal",
    "AED - United Arab Emirates Dirham",
    "TRY - Turkish Lira",
    "ZAR - South African Rand",
    "CHF - Swiss Franc",
  ];
}